### ISSUE TITLE
is there any way to get all links?

### ISSUE THREAD

**Issue by eddie71** [openapi-tools/jackson-dataformat-hal#20]
i have a resource which will have different links depending on the server side configuration. i want to be able to get all links into a list of Hallink objects. i dont know the link names at build time, but they do match a pattern.

**Comment by langecode** [comment]
Let me double check the code - I am not doing much Java these days. But I think you need to know all the possible links in advance - that is compile time. Even though there is actually a class modelling the link as json some of the metadata for generating the link comes from the annotations in your model class. I will double check the code to see if I remember correct.

**Comment by arucard21** [comment]
I think that you need to have each link annotated in the Java class to be recognized as a link. So from the class that you use to deserialize the JSON file, you should know all possible link names as they are just variable names in this class. If you don't know these link names, you may be working with the JSON file directly, without deserializing it to a Java object. This means you're not actually using this library (I think). 

I might have misunderstood the problem. The problem could also be that you do know all possible names but you don't know which ones are returned in each specific resource that's returned. But in that case I think it would be sufficient to just check all possible link variables in the deserialized Java object for whether they are null or not.

You might still wanna wait for @langecode to provide some more info on this but I hope this was helpful.

**Comment by langecode** [comment]
It is indeed true what @arucard21 writes. The metadata for the link is coming from the annotation hence this cannot be configured during runtime as it is.

Not sure if it is still relevant but for future reference what you could do is handle the links "manually" instead of using the `jackson-dataformat-hal` extension. That is create a `Map<string,HALLink>` field in your class and name it (or annotate it) so that it is serialized as `_links`. Then you could populate this field runtime with the links that are relevant at a given time.

I think the reasoning for our initial design choice of having the links defined at compile time is that we had not seen a use case where the set of links were not relatively small and bounded. Hence the readability of the code was much better having the annotations give the metadata for the links.
