### ISSUE TITLE
Add support for @JsonView

### ISSUE THREAD

**Issue by irieill** [openapi-tools/jackson-dataformat-hal#33]
Annotating a class with `@Resource` breaks `@JsonView` behavior. Would be very nice, if both work together. Not only for state properties, but also for links and embedded resources.

**Comment by arucard21** [comment]
I just did a quick test and this does indeed seem to be the case. From what I can tell, I think the problem is that the custom `BeanSerializer` [only uses the `_props` field](https://github.com/openapi-tools/jackson-dataformat-hal/blob/master/src/main/java/io/openapitools/jackson/dataformat/hal/ser/HALBeanSerializer.java#L108) from the `BeanSerializerBase` class it extends. I think it should be using either [`_filteredProps`](https://github.com/FasterXML/jackson-databind/blob/093851341795c1808594699b4e0876907fdb7bd2/src/main/java/com/fasterxml/jackson/databind/ser/bean/BeanSerializerBase.java#L59) or [`_props`](https://github.com/FasterXML/jackson-databind/blob/093851341795c1808594699b4e0876907fdb7bd2/src/main/java/com/fasterxml/jackson/databind/ser/bean/BeanSerializerBase.java#L53), based on whether there's an active view. This is how it's [used in `BeanSerializerBase`](https://github.com/FasterXML/jackson-databind/blob/093851341795c1808594699b4e0876907fdb7bd2/src/main/java/com/fasterxml/jackson/databind/ser/bean/BeanSerializerBase.java#L877). I'm not sure if that's enough to fix it though but it might be a good place to start looking.

Another part to consider is that `@JsonView` is also used on for deserializing. I'm not sure if that's broken right now though.

**Comment by arucard21** [comment]
This was implemented with PR #37.

**Comment by langecode** [comment]
Released with [1.0.9](https://github.com/openapi-tools/jackson-dataformat-hal/releases/tag/v1.0.9)
