### ISSUE TITLE
Update documentation/readme

### ISSUE THREAD

**Issue by irieill** [openapi-tools/jackson-dataformat-hal#35]
Documentation seems somewhat outdated.

- Link to the spec draft returns 404. Should be [https://tools.ietf.org/html/draft-kelly-json-hal-08](url)
- Sample code and description contains `@Embedded`. Should be updated to `@EmbeddedResource`. This was very confusing when i discoverd this project.
- Sample code contains simple `HALLink` fields only. Should show that e.g. `Collection<HALLink>` is supported as well. Only got this by looking into the code.

**Comment by arucard21** [comment]
I created pull request #36 to update the URL and fix the annotation. I didn't add the example for `Collection <HALLink>` since it requires rewriting the documentation. It should be simple enough to add later. Feel free to rewrite it yourself and submit another pull request for that. 

If you do, you might want to look at the CURIEs example as well. I think it might also be incorrect since it has an embedded resource which don't seem to be available in the Java class and the CURIEs name in the annotation doesn't seem to correspond to the one in the JSON. 

Thanks for your feedback.

**Comment by langecode** [comment]
Thanks for the contribution once again @arucard21
