### ISSUE TITLE
Fix build issues from #37

### ISSUE THREAD

**Issue by langecode** [openapi-tools/jackson-dataformat-hal#40]
Seems PR #37 resulted in build failures this must be fixed.

**Comment by arucard21** [comment]
I've looked into this and I think it might be because the tests are running as integration tests instead of unit tests (using Failsafe plugin instead of Surefire plugin). When I change the tests to unit tests (renaming them from *IT.java to *Test.java), it seems to behave more consistently. But I still get a failing test due to NPE, though now it consistently fails on Java 8 as well as 11. But strangely only with Maven, not when running it directly in the IDE. I'll see if I can find the problem with this.

**Comment by arucard21** [comment]
You can ignore my previous comment. That wasn't the problem. 

From what I can tell, it seems like these 2 tests are flaky but I don't know why.
`HALBeanDeserializerJsonViewIT#testDeserializationOfViewWithInclusion`
`HALBeanSerializerJsonViewIT#testSerializationOfViewWithInclusion`

If I run `mvn clean verify` a few times, one or both of these tests will sometimes fail. This happens with both Java 8 and Java 11 so it doesn't seem related to the JVM version.

**Comment by arucard21** [comment]
I found the problem. The "default inclusion" feature was being set globally. But I think Maven runs the tests in parallel so it would sometimes be set incorrectly for the test if another test changed the feature setting. When using a HALMapper created and configured within the test, it seems to work fine. I ran `mvn clean verify` several times now and it seems to consistently pass. I'll create a PR for this.
